import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import NavBar from "@/ui/navtopBar/NavBar";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

import { Suspense } from "react";
import Main from "@/ui/Main/Main";
import Queue from "@/ui/Queue/Queue";
import AudioFooterBar from "@/ui/Footer/AudioFooterBar";
import Footer from "@/ui/Footer/Footer";
import QueueWrapper from "@/ui/Queue/QueueWrapper";
import QueryClientPrv from "@/lib/tanstack/QueryClient";
import BeforeLoad from "@/ui/warning/BeforeLoad";
import ModalBox from "@/ui/general/modalBox/ModalBox";
import { ThemeProvider } from "next-themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon.ico" },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};
import NextTopLoader from "nextjs-toploader";

import AudioWrapper from "@/ui/Footer/audio/AudioWrapper";
import LibandLikeHyration from "@/lib/HydrationData/LibandLikeHyration";
import LoadingAudioPlayer from "@/ui/loading/LoadingAudioPlayer";
import DeviceCheckFetcher from "@/lib/DeviceContext/DeviceCheckFetcher";
import QueueNotFullScreen from "@/ui/Queue/QueueNotFullScreen";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full bg-background text-foreground"
      suppressHydrationWarning
    >
      <body
        className={`${inter.className} overflow-hidden relative h-full flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientPrv>
            <Suspense fallback={<div>loading....</div>}>
              <NextIntlClientProvider>
                <DeviceCheckFetcher>
                  <LibandLikeHyration>
                    <NextTopLoader
                      color="var(--loader)"
                      initialPosition={0.08}
                      crawlSpeed={200}
                      height={3}
                      crawl={true}
                      showSpinner={false}
                      easing="ease"
                      speed={200}
                      shadow="0 0 10px var(--loader),0 0 5px var(--loader)"
                      template='<div class="bar" role="bar"><div class="peg"></div></div>' // no spinner
                      zIndex={1600}
                      showAtBottom={false}
                    />
                    <AudioWrapper>
                      <BeforeLoad />
                      <NavBar />
                      <div className="scr flex flex-1 overflow-hidden relative">
                        <Main>
                          {children}
                          <Footer />
                        </Main>
                        <QueueWrapper>
                          <Queue wrapper={QueueNotFullScreen} />
                        </QueueWrapper>

                        <ModalBox />
                      </div>
                      <Suspense fallback={<LoadingAudioPlayer />}>
                        <AudioFooterBar />
                      </Suspense>
                    </AudioWrapper>
                  </LibandLikeHyration>
                </DeviceCheckFetcher>
              </NextIntlClientProvider>
            </Suspense>
          </QueryClientPrv>
        </ThemeProvider>
      </body>
    </html>
  );
}
