import type { Metadata } from "next";
import { ReactNode, Suspense } from "react";
import "../../../globals.css";
import { Geist } from "next/font/google";
import { ThemeProvider } from "next-themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon.ico" },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  display: "swap",
  subsets: ["latin"],
});
import NextTopLoader from "nextjs-toploader";
import DeviceCheckFetcher from "@/lib/DeviceContext/DeviceCheckFetcher";
import { NextIntlClientProvider } from "next-intl";
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className}  antialiased`}>
        <NextTopLoader
          color="var(--loader)"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false} // still good to include
          easing="ease"
          speed={200}
          shadow="0 0 10px var(--loader),0 0 5px var(--loader)"
          template='<div class="bar" role="bar"><div class="peg"></div></div>' // no spinner
          zIndex={1600}
          showAtBottom={false}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={<div>loading...</div>}>
            <NextIntlClientProvider>
              <DeviceCheckFetcher>{children}</DeviceCheckFetcher>
            </NextIntlClientProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
