import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "next-themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon.ico" },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};
import NextTopLoader from "nextjs-toploader";
import { NextIntlClientProvider } from "next-intl";
import { Suspense } from "react";
import AppLoading from "@/ui/loading/AppLoading";
import { Toaster } from "sonner";
import DeviceCheckFetcher from "@/lib/DeviceCheck/DeviceCheckFetcher";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full bg-background text-foreground"
      suppressHydrationWarning
    >
      <body
        className={`${inter.className} overflow-hidden relative h-full flex flex-col`}
      >
        <Toaster
          position="bottom-center"
          toastOptions={{
            duration: 2000,
          }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader
            color="var(--loader)"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px var(--loader),0 0 5px var(--loader)"
            template='<div class="bar" role="bar"><div class="peg"></div></div>' // no spinner
            zIndex={1600}
            showAtBottom={false}
          />
          <Suspense fallback={<AppLoading />}>
            <NextIntlClientProvider>
              <DeviceCheckFetcher>{children}</DeviceCheckFetcher>
            </NextIntlClientProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
